#!/usr/bin/env python3
"""
This module provides an asynchronous list comprehension that
returns a list of floats generated by the async_generator function
from the '0-async_generator' module.
"""
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:

    return [i async for i in async_generator()]
